---
- name: Install Wordpress
  hosts: webserver
  become: true
  vars_files:
    - vars/default.yml
  
  tasks:
    # Update all packages
    - name: Update apt cache
      apt:
        update_cache: yes
  
    # Install required packaged for installing wordpress
    - name: Install packages for wordpress
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ required_packages  }}"
    
    # Set the root password
    - name: Set the root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    # Create mysql database for wordpress
    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
    
    # Create mysql user for wordpress
    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    # Download latest wordpress version and save it to tmp folder
    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    # Unarchive the wordpress and put all the files into Apache 2 directory
    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes
        extra_opts: "--strip-components=1" # Strip wordpress folder

    # It creates wp-config.php and sets the database
    - name: Create wp-config.php and set database
      blockinfile:
        create: true
        marker: "" # Empty mark since default has value
        path: /var/www/html/wp-config.php
        state: present
        block: |
          <?php
          define( 'DB_NAME', '{{ mysql_db }}' );
          define( 'DB_USER', '{{ mysql_user }}' );
          define( 'DB_PASSWORD', '{{ mysql_password }}' );
          define( 'DB_HOST', 'localhost' );
          define( 'DB_CHARSET', 'utf8' );
          define( 'DB_COLLATE', '' );

          define( 'AUTH_KEY',         'put your unique phrase here' );
          define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
          define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
          define( 'NONCE_KEY',        'put your unique phrase here' );
          define( 'AUTH_SALT',        'put your unique phrase here' );
          define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
          define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
          define( 'NONCE_SALT',       'put your unique phrase here' );

          $table_prefix = 'wp_';
          define( 'WP_DEBUG', false );
          if ( ! defined( 'ABSPATH' ) ) {
                  define( 'ABSPATH', __DIR__ . '/' );
          }
          require_once ABSPATH . 'wp-settings.php';

    # Delete the index.html file
    - name: Delete index.html file
      file:
        path: /var/www/html/index.html
        state: absent

    # Enable apache module which will ensure that rewrite rules in wordpress works properly
    - name: Enable Apache rewrite module
      apache2_module:
        state: present
        name: rewrite

    # Enable php module that will allow to process php scripts
    - name: Enable PHP module
      apache2_module:
        state: present
        name: php

     # Restart apache
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
